apiVersion: v1
kind: Service
metadata:
  name: hello-aranya
  namespace: hello-aranya
  labels:
    app: hello-aranya
spec:
  type: NodePort
  selector:
    app: hello-aranya
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080   # reachable at http://<any-node-public-ip>:30080
