replicaCount: 1

image:
  repository: redis:8.8.0
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Values.service.port  
port: 6379
